f1 = aplpy.FITSFigure(q_in, figure=fig, subplot=[0.05,0.05,0.25,0.90])
f1.tick_labels.set_font(size='large')
#f1.axis_labels.set_font(size='small')
#f1.axis_labels.hide()
#f1.tick_labels.hide()
f1.show_colorscale(cmap='afmhot', vmin=-0.05, vmax=0.10)
x_coord,y_coord=f1.pixel2world(center_pix_x[chunk],center_pix_y[chunk])
f1.recenter(x_coord,y_coord,width=width_deg,height=width_deg)
f1.add_colorbar()
f1.colorbar.set_font(size='small')
f1.colorbar.set_axis_label_text('K')
f1.axis_labels.set_xtext("RA")
f1.axis_labels.set_ytext("Dec")
#f1.axis_labels.hide_x()
#f1.tick_labels.hide_x()
f1.tick_labels.set_xformat('hh:mm')
f1.tick_labels.set_yformat('dd')
#f1.axis_labels.hide_x()
#f1.add_label(0.1,0.1,'P',relative=True, color='white', size='18', weight='bold')
f1.add_label(0.1,0.1,'Q',relative=True, color='black', size='18', weight='bold')
